# Generated by Django 4.2.23 on 2025-08-03 17:20

from django.db import migrations, models
import django.db.models.manager


class Migration(migrations.Migration):

    dependencies = [
        ('messaging', '0002_message_edited_message_parent_message_and_more'),
    ]

    operations = [
        migrations.AlterModelManagers(
            name='message',
            managers=[
                ('unread', django.db.models.manager.Manager()),
            ],
        ),
        migrations.AddField(
            model_name='message',
            name='read',
            field=models.BooleanField(default=False),
        ),
    ]
