version: "3.9"

services:
  db:
    image: mysql:8.0
    container_name: messaging_db
    restart: always
    env_file:
      - .env
    environment:
      - MYSQL_DATABASE=${DOCKER_DB_NAME}
      - MYSQL_USER=${DOCKER_DB_USER}
      - MYSQL_PASSWORD=${DOCKER_DB_PASSWORD}
      - MYSQL_ROOT_PASSWORD=${DOCKER_DB_ROOT_PASSWORD}
    ports:
      - "3307:3306"
    volumes:
      - db_data:/var/lib/mysql

  web:
    build: .
    command: python manage.py runserver 0.0.0.0:8000
    container_name: messaging_app
    volumes:
      - .:/app
    ports:
      - "8000:8000"
    env_file:
      - .env
    environment:
      - APP_ENV=docker   # Force Django to use Docker DB config
    depends_on:
      - db

volumes:
  db_data:
